name: gbgm_predictor_app
description: A Flutter app to predict GBGM game numbers.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # Uncomment and edit this if you're using images/fonts
  # assets:
  #   - assets/images/
